### PR TITLE
fixed map zoom interfearing with scroll

### PR DESCRIPTION
**Pull request by arvindamirtaa**
When we're scrolling through the page and get to the venue maps, the scroll gets stuck and starts zooming the map. Added leaflet-sleep.js to fix that.

### CODE REVIEW

**Comment by arvindamirtaa** [comment]
My apologies for the mess. I pushed the commits in master instead of an issue specific branch by mistake. But didn't bother changing it as the fixes were fairly minor. If it's absolutely an issue, I'll change it.

**Comment by sayanchowdhury** [comment]
Thanks @arvindamirtaa for this PR. A much needed one.

I was wondering if this can be implemented in this way that you need to click to zoom and not have the note box in there.

**Comment by arvindamirtaa** [comment]
I believe it is. Let me play around with the configs and see if I can.

**Comment by arvindamirtaa** [comment]
It was just a config thing. Pl check now.

**Comment by sayanchowdhury** [comment]
Going ahead with merge :fireworks:

**Comment by sayanchowdhury** [comment]
Thanks again.

You can join #pyconpune on Freenode IRC. We are actively discussing things there so you can chip in too.

**Pull request merged**
