### PR TITLE
Added lineart image for pune : Pycon 2018

### PR DESCRIPTION
**Pull request by a2batic**
Signed-off-by: a2batic <murarkakanika@gmail.com>

### CODE REVIEW

**Comment by SaptakS** [comment]
@a2batic thanks. Can you please specify which page or section this is meant for?

**Comment by a2batic** [comment]
@SaptakS, It might suit About page of website[1]. I think @sayanchowdhury can guide better.
[1] https://pune.pycon.org/2018/about/

**Comment by a2batic** [comment]
@SaptakS, updated the lineart and added svg file.

**Comment by SaptakS** [comment]
@a2batic looks good to me.

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
